name: z-os toolchain
description: Use the z-os toolchain
inputs:
  script:
    description: Script to run
    required: true
runs:
  using: docker
  image: docker://imzacm/z-os-toolchain:v0.1.13
  args:
    - ${{ inputs.script }}
